Repository holaluz/margarita, pull requests merged in 2021-01, with the labels that each got.

#315 feat: Remove MaGrid
  .storybook/preview.js
  .storybook/webpack.config.js
  package-lock.json
  package.json
  src/components/MaAlert/MaAlert.stories.js
  src/components/MaButton/MaButton.stories.js
  src/components/MaCard/MaCard.stories.js
  src/components/MaDatagrid/MaDatagrid.stories.js
  src/components/MaGridColumn/MaGridColumn.scss
  src/components/MaGridColumn/MaGridColumn.spec.js
  src/components/MaGridColumn/MaGridColumn.vue
  src/components/MaGridColumn/index.js
  src/components/MaGridContainer/MaGridContainer.scss
  src/components/MaGridContainer/MaGridContainer.spec.js
  src/components/MaGridContainer/MaGridContainer.stories.js
  src/components/MaGridContainer/MaGridContainer.vue
  src/components/MaGridContainer/index.js
  src/components/MaGridContainer/stories.scss
  src/components/MaGridRow/MaGridRow.scss
  src/components/MaGridRow/MaGridRow.spec.js
  src/components/MaGridRow/MaGridRow.vue
  src/components/MaGridRow/index.js
  src/components/MaIcon/MaIcon.stories.js
  src/components/MaOption/MaOption.stories.js
  src/components/MaOption/MaOption.vue
  src/components/MaPagination/MaPagination.stories.js
  src/components/MaPill/MaPill.stories.js
  src/components/MaRange/MaRange.stories.js
  src/components/MaSelect/MaSelect.stories.js
  src/components/MaStack/MaStack.stories.js
  src/components/MaTextField/MaTextField.stories.js
  src/components/colors.stories.js
  src/directives/markdown/markdown.stories.js
  src/index.js
  src/scss/_margarita-tokens.scss
  src/scss/mixins/_breakpoints.scss
  src/scss/mixins/_grid.scss
  src/scss/variables/_fonts.scss
  src/scss/variables/_grid.scss
  src/scss/variables/_sass-mq.scss
Labels: Release: major, not ready to merge

#317 feat: Autogenerate component & prop autocompletion for Margarita components
  .gitignore
  package-lock.json
  package.json
Labels: Release: minor

#319 feat: Generate CSS custom properties
  .gitignore
  package.json
  src/index.js
  style-dictionary.config.js
Labels: Release: minor

#316 feat: Change layout spacing names and values
  src/components/MaStack/MaStack.stories.js
  src/tokens/spacing.js
Labels: Design System, Release: major

#289 feat: Add MaHidden
  src/components/MaHidden/MaHidden.js
  src/components/MaHidden/MaHidden.spec.js
  src/components/MaHidden/MaHidden.stories.js
  src/components/MaHidden/index.js
  src/index.js
Labels: Design System, Release: minor

#322 docs: Replace deprecated space naming by the new valid one
  src/components/MaAlert/MaAlert.stories.js
  src/components/MaPill/MaPill.stories.js
Labels: bug

#323 fix: Remove rem function usage
  src/components/MaAlert/MaAlert.scss
  src/components/MaButton/MaButton.scss
  src/components/MaCard/MaCard.scss
  src/components/MaDatagrid/MaDatagrid.scss
  src/components/MaDatagrid/components/MaDatagridLoader.scss
  src/components/MaOption/MaOption.scss
  src/components/MaOption/MaOptionCheckbox.scss
  src/components/MaOption/MaOptionRadio.scss
  src/components/MaPagination/MaPagination.scss
  src/components/MaPill/MaPill.scss
  src/components/MaRange/MaRange.scss
  src/components/MaSelect/MaSelect.scss
  src/components/MaSidebar/MaSidebar.scss
  src/components/MaTextField/MaTextField.scss
  src/components/MaTextField/MaTextField.stories.js
Labels: Release: patch

#328 fix: Fix dashed names on tokens
  .style-dictionary/build.js
  .style-dictionary/tokens.js
  package.json
  style-dictionary.config.js
Labels: Release: patch

#303 feat: Add MaModal
  package-lock.json
  package.json
  src/components/MaModal/MaModal.css
  src/components/MaModal/MaModal.spec.js
  src/components/MaModal/MaModal.stories.js
  src/components/MaModal/MaModal.vue
  src/components/MaModal/index.js
  src/index.js
Labels: Design System, Release: minor
