Repository holaluz/margarita, pull requests merged in 2021-02, with the labels that each got.

#327 feat: Add MaText component
  src/components/MaText/MaText.css
  src/components/MaText/MaText.spec.js
  src/components/MaText/MaText.stories.js
  src/components/MaText/MaText.vue
  src/components/MaText/index.js
  src/index.js
  src/tokens/index.js
  src/tokens/text.js
  src/tokens/tones.js
Labels: Design System, Release: minor

#347 feat(Stack): Add fill value for align prop
  src/components/MaStack/MaStack.spec.js
  src/components/MaStack/MaStack.vue
  vetur/attributes.json
Labels: Release: minor

#341 docs: Add introduction docs to storybook
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview.js
  .storybook/public/images/holaluz.svg
  .storybook/public/images/margarita.png
  README.md
  docs/README.md
  docs/components/MaAlert.docs.mdx
  docs/components/MaButton.docs.mdx
  docs/components/MaCard.docs.mdx
  docs/components/MaDataGrid.docs.mdx
  docs/components/MaHidden.docs.mdx
  docs/components/MaIcon.docs.mdx
  docs/components/MaModal.docs.mdx
  docs/components/MaOption.docs.mdx
  docs/components/MaPagination.docs.mdx
  docs/components/MaPill.docs.mdx
  docs/components/MaRange.docs.mdx
  docs/components/MaSelect.docs.mdx
  docs/components/MaStack.docs.mdx
  docs/components/MaText.docs.mdx
  docs/components/MaTextField.docs.mdx
  docs/introduction/design-principles.stories.mdx
  docs/introduction/getting-started.stories.mdx
  docs/introduction/welcome.stories.mdx
  docs/tokens/colors.docs.mdx
  docs/tokens/colors.stories.js
  package-lock.json
  package.json
  src/components/MaAlert/MaAlert.stories.js
  src/components/MaButton/MaButton.stories.js
  src/components/MaCard/MaCard.stories.js
  src/components/MaDatagrid/MaDatagrid.stories.js
  src/components/MaHidden/MaHidden.stories.js
  src/components/MaIcon/MaIcon.stories.js
  src/components/MaModal/MaModal.stories.js
  src/components/MaOption/MaOption.stories.js
  src/components/MaPagination/MaPagination.stories.js
  src/components/MaPill/MaPill.stories.js
  src/components/MaRange/MaRange.stories.js
  src/components/MaSelect/MaSelect.stories.js
  src/components/MaStack/MaStack.stories.js
  src/components/MaText/MaText.stories.js
  src/components/MaTextField/MaTextField.stories.js
Labels: Design System

#355 docs: Add Spacing tokens doc
  docs/tokens/spacing.stories.mdx
  src/components/MaHeading/MaHeading.vue
  src/components/MaStack/MaStack.vue
  src/components/MaText/MaText.vue
  vetur/attributes.json
Labels: Design System

#354 feat: add css vars for gradients
  .style-dictionary/tokens.js
  docs/tokens/colors.docs.mdx
  docs/tokens/colors.stories.js
  docs/tokens/colors.stories.mdx
  docs/tokens/gradients.stories.mdx
  src/components/MaModal/MaModal.css
  src/components/MaRange/MaRange.css
  src/css/tokens.css
  src/scss/_tokens.scss
  src/tokens/gradient.js
  src/tokens/index.js
Labels: Design System, Release: minor
